name: Bun CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest  # Puedes especificar una versión específica si lo prefieres

      - name: Install dependencies
        run: bun install

      # Descomentar si tienes configuración para lint
      # - name: Run lint
      #   run: bun lint

      - name: Run build
        run: bun run build --if-present

      # Descomentar si tienes configuración para tests
      # - name: Run tests
      #   run: bun test
