name: Bun CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]
    steps:
      - uses: actions/checkout@v1

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
        shell: bash

      - name: Add Bun to PATH
        run: |
          echo 'export BUN_INSTALL="$HOME/.bun"' >> $GITHUB_ENV
          echo 'export PATH="$BUN_INSTALL/bin:$PATH"' >> $GITHUB_ENV
        shell: bash

      - name: Install dependencies
        run: |
          bun install

      - name: Run build
        run: |
          bun run build --if-present

      # Descomentar los siguientes pasos si tienes lint y tests configurados
      # - name: Run lint
      #   run: |
      #     bun lint

      # - name: Run tests
      #   run: |
      #     bun test
